apiVersion: apps/v1
kind: Deployment
metadata:
  name:  &name ${DEPLOYMENT_NAME}
  labels:
    app: *name
spec:
  replicas: ${REPLICAS}
  selector:
    matchLabels:
      app: *name
  template:
    metadata:
      labels:
        app: *name
    spec:
      containers:
      - name: *name
        image: ${IMAGE_NAME}:${IMAGE_TAG}
        imagePullPolicy: "Always"
        ports:
        - containerPort: ${APP_PORT}
