apiVersion: v1
kind: Service
metadata:
  name: &name ${DEPLOYMENT_NAME}
  labels:
    tier: backend
    version: v1
spec:
  externalTrafficPolicy: Cluster
  ports:
  - name: http
    nodePort: 30001
    port: 80
    protocol: TCP
    targetPort: ${APP_PORT}
  selector:
    app: *name
  type: NodePort
